version: "3"

services:
  mongo:
    image: mongo:4.4.6
    container_name: dexscreener_mongodb
    restart: always
    volumes:
      - database:/data/mongo
    env_file:
      - .env
    ports:
      - 27017:27017

volumes:
  database:
